=== Ainkill/data/schema.json
{
	"$schema": "http://json-schema.org/draft-03/schema#",
	"type": "object",
	"properties": {
		"slug": {
			"type": "string",
			"title": "Slug",
			"required": true
		},
		"categories": {
			"type": "array",
			"title": "Categories",
			"uniqueItems": true,
			"items": {
				"type": "string"
			}
		},
		"name": {
			"type": "string",
			"title": "Name",
			"required": true
		},
		"runs": {
			"type": "array",
			"title": "Runs",
			"uniqueItems": true,
			"items": {
				"type": "string"
			}
		},
		"address": {
			"type": "string",
			"title": "Address",
			"format": "text",
			"required": true
		},
		"phone": {
			"type": "string",
			"title": "Phone"
		},
		"fax": {
			"type": "string",
			"title": "Fax"
		},
		"email": {
			"type": "string",
			"title": "E-mail"
		},
		"web": {
			"type": "string",
			"title": "Website"
		},
		"sources": {
			"type": "array",
			"title": "Sources",
			"uniqueItems": true,
			"items": {
				"type": "string"
			},
			"required": true
		},
		"required-elements-access": {
			"type": "array",
			"title": "Access elements",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"desc": {
						"type": "string",
						"title": "Description",
						"required": true
					},
					"type": {
						"type": "string",
						"title": "Type",
						"required": true,
						"default": "input",
						"enum": [ "input", "textarea", "address" ]
					},
					"optional": {
						"type": "boolean",
						"title": "Optional?"
					}
				}
			}
		},
		"required-elements-erasure": {
			"type": "array",
			"title": "Erasure elements",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"desc": {
						"type": "string",
						"title": "Description",
						"required": true
					},
					"type": {
						"type": "string",
						"title": "Type",
						"required": true,
						"default": "input",
						"enum": [ "input", "textarea", "address" ]
					},
					"optional": {
						"type": "boolean",
						"title": "Optional?"
					}
				}
			}
		},
		"custom-access-template": {
			"type": "string",
			"title": "Custom access template"
		},
		"custom-erasure-template": {
			"type": "string",
			"title": "Custom erasure template"
		},
		"comments": {
			"type": "array",
			"title": "Comments",
			"items": {
				"type": "string",
				"format": "text"
			}
		}
	}
}

=== Ainkill/data/data/hertz.json
{
    "slug": "hertz",
    "categories": [
        "travel"
    ],
    "name": "Hertz Autovermietung GmbH",
    "runs": [
        "Hertz Gold Plus Rewards",
        "Hertz 24/7",
        "Hertz NeverLost.com"
    ],
    "address": "Ludwig-Erhard-Stra√üe 12\n65760 Eschborn\nDeutschland",
    "phone": "+49 6196 937 0",
    "fax": "+49 6196 937 289",
    "email": "alpha_de@hertz.com",
    "web": "https://www.hertz.de",
    "sources": [
        "https://www.hertz.de/rentacar/privacypolicy/index.jsp?targetPage=privacyPolicyView.jsp",
        "https://www.hertz.de/rentacar/misc/simpleIndex.jsp?targetPage=Impressum.xml"
    ]
}

=== Ainkill/data/data/easybell.json
{
    "slug": "easybell",
    "categories": [
        "telecommunication"
    ],
    "name": "easybell GmbH",
    "address": "Datenschutzbeauftragter\nMagazinstraße 15 – 16\n10179 Berlin\nDeutschland",
    "phone": "+49 30 80 95 1081",
    "fax": "+49 30 80 95 1009",
    "email": "datenschutz@easybell.de",
    "web": "https://www.easybell.de/",
    "sources": [
        "https://www.easybell.de/datenschutz.html",
        "https://www.easybell.de/impressum.html"
    ]
}

=== Ainkill/data/data/jako-o.json
{
    "slug": "jako-o",
    "categories": [
        "Handel"
    ],
    "name": "Jako-o Möbel und Spielmittel für die junge Familie GmbH",
    "runs": [
        "Mein JAKO-O"
    ],
    "address": "Datenschutz\n96475 Bad Rodach\nDeutschland",
    "phone": "+49 9564 929 11 12",
    "fax": "+49 9564 929 662 500",
    "email": "service@jako-o.de",
    "web": "https://www.jako-o.de/",
    "sources": [
        "https://www.jako-o.de/--00003009/",
        "https://www.jako-o.de/--00003011/"
    ]
}

=== Ainkill/data/data/vr-bank.json
{
    "slug": "vr-bank",
    "categories": [
        "Bank"
    ],
    "name": "Bundesverband der Deutschen Volksbanken und Raiffeisenbanken e.V. (BVR)",
    "address": "Datenschutzbeauftragter\nSchellingstra√üe 4\n10785 Berlin\nDeutschland",
    "phone": "+49 30 2021 0",
    "fax": "+49 30 2021 1900",
    "email": "info@bvr.de",
    "web": "https://www.vr.de/privatkunden.html",
    "sources": [
        "https://www.vr.de/privatkunden/service/datenschutz.html",
        "https://www.vr.de/privatkunden/service/impressum.html"
    ]
}

=== Ainkill/data/data/allyouneed.json
{
    "slug": "allyouneed",
    "categories": [
        "commerce"
    ],
    "name": "All you need GmbH",
    "runs": [
        "Allyouneed Marketplatz",
        "AllyouneedFresh (allyouneedfresh.de)"
    ],
    "address": "Herrn Jens Drubel\nFriedrichstra√üe 210\n10969 Berlin\nDeutschland",
    "phone": "+49 30 609 840 40",
    "email": "datenschutz@allyouneedfresh.de",
    "web": "https://de.allyouneed.com",
    "sources": [
        "https://www.allyouneedfresh.de/kundenservice/datenschutz",
        "https://www.allyouneedfresh.de/kundenservice/impressum"
    ],
    "comments": [
        "Auf der Webseite von Allyouneed wird die DHL Paket GmbH als Betreiber angeben."
    ]
}

=== Ainkill/data/data/vattenfall.json
{
    "slug": "vattenfall",
    "categories": [
        "utility"
    ],
    "name": "Vattenfall GmbH",
    "runs": [
        "Vattenfall Europe Sales GmbH",
        "Vattenfall Wärme Berlin AG",
        "Vattenfall Wärme Hamburg GmbH",
        "Vattenfall Real Estate Energy Sales GmbH",
        "Vattenfall Europe Innovation GmbH",
        "Vattenfall Smarter Living GmbH",
        "Mein Vattenfall"
    ],
    "address": "Datenschutzbeauftragter\nChausseestraße 23\n10115 Berlin\nDeutschland",
    "phone": "+49 40 657 988 000",
    "email": "datenschutz@vattenfall.de",
    "web": "https://www.vattenfall.de/",
    "sources": [
        "https://www.vattenfall.de/de/datenschutz.htm",
        "https://www.vattenfall.de/de/impressum.htm"
    ]
}

=== Ainkill/data/data/hermes.json
{
    "slug": "hermes",
    "categories": [
        "Handel"
    ],
    "name": "Hermes Germany GmbH",
    "address": "Datenschutzbeauftragter\nEssener Stra√üe 89\n22419 Hamburg\nDeutschland",
    "phone": "+49 40 53755 0",
    "fax": "+49 40 53754 870",
    "email": "datenschutz@hermesworld.com",
    "web": "https://www.myhermes.de/",
    "sources": [
        "https://www.myhermes.de/datenschutz/",
        "https://www.myhermes.de/impressum/"
    ],
    "required-elements-access": [
        {
            "desc": "Name",
            "type": "input"
        },
        {
            "desc": "Adresse",
            "type": "address"
        }
    ],
    "comments": [
        "Erbitten datenschutzspezifische Anfragen per E-Mail zur schnelleren Bearbeitung."
    ]
}

=== Ainkill/data/data/roland-rechtsschutz.json
{
    "slug": "roland-rechtsschutz",
    "categories": [
        "Versicherung"
    ],
    "name": "ROLAND-Gruppe",
    "runs": [
        "ROLAND Rechtsschutz-Versicherungs-AG",
        "ROLAND Schutzbrief-Versicherung AG",
        "ROLAND Assistance GmbH",
        "ROLAND AssistancePartner GmbH"
    ],
    "address": "Datenschutzbeauftragter Heinz-Peter Voss\nDeutz-Kalker Straße 46\n50679 Köln\nDeutschland",
    "phone": "+49 221 8277 500",
    "fax": "+49 221 8277 460",
    "email": "datenschutz@roland-ag.de",
    "web": "https://www.roland-rechtsschutz.de",
    "sources": [
        "https://www.roland-rechtsschutz.de/datenschutz/datenschutz.html",
        "https://www.roland-rechtsschutz.de/impressum/impressum.html"
    ]
}
