=== Ainkill/data/schema.json
{
	"$schema": "http://json-schema.org/draft-03/schema#",
	"type": "object",
	"properties": {
		"slug": {
			"type": "string",
			"title": "Slug",
			"required": true
		},
		"categories": {
			"type": "array",
			"title": "Categories",
			"uniqueItems": true,
			"items": {
				"type": "string"
			}
		},
		"name": {
			"type": "string",
			"title": "Name",
			"required": true
		},
		"runs": {
			"type": "array",
			"title": "Runs",
			"uniqueItems": true,
			"items": {
				"type": "string"
			}
		},
		"address": {
			"type": "string",
			"title": "Address",
			"format": "text",
			"required": true
		},
		"phone": {
			"type": "string",
			"title": "Phone"
		},
		"fax": {
			"type": "string",
			"title": "Fax"
		},
		"email": {
			"type": "string",
			"title": "E-mail"
		},
		"web": {
			"type": "string",
			"title": "Website"
		},
		"sources": {
			"type": "array",
			"title": "Sources",
			"uniqueItems": true,
			"items": {
				"type": "string"
			},
			"required": true
		},
		"required-elements-access": {
			"type": "array",
			"title": "Access elements",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"desc": {
						"type": "string",
						"title": "Description",
						"required": true
					},
					"type": {
						"type": "string",
						"title": "Type",
						"required": true,
						"default": "input",
						"enum": [ "input", "textarea", "address" ]
					},
					"optional": {
						"type": "boolean",
						"title": "Optional?"
					}
				}
			}
		},
		"required-elements-erasure": {
			"type": "array",
			"title": "Erasure elements",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"desc": {
						"type": "string",
						"title": "Description",
						"required": true
					},
					"type": {
						"type": "string",
						"title": "Type",
						"required": true,
						"default": "input",
						"enum": [ "input", "textarea", "address" ]
					},
					"optional": {
						"type": "boolean",
						"title": "Optional?"
					}
				}
			}
		},
		"custom-access-template": {
			"type": "string",
			"title": "Custom access template"
		},
		"custom-erasure-template": {
			"type": "string",
			"title": "Custom erasure template"
		},
		"comments": {
			"type": "array",
			"title": "Comments",
			"items": {
				"type": "string",
				"format": "text"
			}
		}
	}
}

=== Ainkill/data/data/aboutyou-shop.json
{
    "slug": "aboutyou-shop",
    "categories": [
        "commerce"
    ],
    "name": "ABOUT YOU GmbH",
    "address": "Domstra√üe 10\n20095 Hamburg\nDeutschland",
    "phone": "+49 40 638 569 100",
    "email": "kundenservice@aboutyou.de",
    "web": "https://www.aboutyou.de",
    "sources": [
        "https://www.aboutyou.de/datenschutz",
        "https://www.aboutyou.de/impressum"
    ]
}

=== Ainkill/data/data/zalando.json
{
    "slug": "zalando",
    "categories": [
        "Handel"
    ],
    "name": "Zalando SE",
    "address": "Tamara-Danz-Stra√üe 1\n10243 Berlin\nDeutschland",
    "phone": "+49 800 33 00 900",
    "fax": "+49 30 2759 46 93",
    "email": "datenschutz@zalando.de",
    "web": "https://www.zalando.de/",
    "sources": [
        "https://www.zalando.de/zalando-datenschutz/",
        "https://www.zalando.de/zalando-impressum/"
    ]
}

=== Ainkill/data/data/acxiom.json
{
    "slug": "acxiom",
    "categories": [
        "Adressen"
    ],
    "name": "Acxiom Deutschland GmbH",
    "address": "Martin-Behaim Stra√üe 12\n63263 Neu-Isenburg\nDeutschland",
    "phone": "+49 6102 736 3",
    "fax": "+49 6102 736 444",
    "email": "datenschutz@acxiom.com",
    "web": "http://www.acxiom.de/",
    "sources": [
        "http://www.acxiom.de/datenschutz/",
        "http://www.acxiom.de/impressum/",
        "https://marketing.acxiom.com/AcxiomDE-Verbraucheranfragen.html"
    ],
    "required-elements-access": [
        {
            "desc": "Name",
            "type": "input"
        },
        {
            "desc": "Geburtsdatum",
            "type": "input"
        },
        {
            "desc": "Adresse",
            "type": "address"
        }
    ]
}

=== Ainkill/data/data/tnt.json
{
    "slug": "tnt",
    "categories": [
        "commerce"
    ],
    "name": "TNT Express GmbH",
    "runs": [
        "TNT Paketdienst",
        "TNT Express"
    ],
    "address": "Datenschutzbeauftragter\nHaberstra√üe 2\n53842 Troisdorf\nDeutschland",
    "phone": "+49 22 41 497 0",
    "fax": "+49 22 41 497 66 65",
    "email": "datenschutz@tnt.de",
    "web": "https://www.tnt.com/express/de_de/site/home.html",
    "sources": [
        "https://www.tnt.com/express/de_de/site/home/terms-conditions.html",
        "https://www.tnt.com/express/de_de/site/home/Impressum.html"
    ]
}

=== Ainkill/data/data/home24.json
{
    "slug": "home24",
    "categories": [
        "Handel"
    ],
    "name": "Home24 AG",
    "runs": [
        "Smood (www.smood-sleep.de)",
        "Black Friday Möbel (www.black-friday-moebel.de)"
    ],
    "address": "Greifswalder Straße 212 – 213\n10405 Berlin\nDeutschland",
    "phone": "+49 30 20 38 99 66",
    "fax": "+49 30 60 98 80 06 3",
    "email": "datenschutz@home24.de",
    "web": "https://www.home24.de/",
    "sources": [
        "https://www.home24.de/datenschutz/",
        "https://www.home24.de/impressum/"
    ]
}

=== Ainkill/data/data/riskident.json
{
    "slug": "riskident",
    "categories": [
        "Auskunftei"
    ],
    "name": "Risk.Ident GmbH",
    "address": "Am Sandtorkai 50\n20457 Hamburg\nDeutschland",
    "phone": "+49 40 60945 2590",
    "email": "contact@riskident.com",
    "web": "https://riskident.com",
    "comments": [
        "Externer Datenschutzbeauftragter: Christian Mommers, intersoft consulting services AG, Frankenstra√üe 18a, 20097 Hamburg, Deutschland.\nTelefon: +49 40 7902350, E-Mail: cmommers@intersoft-consulting.de"
    ]
}

=== Ainkill/data/data/tchibo.json
{
    "slug": "tchibo",
    "categories": [
        "commerce"
    ],
    "name": "Tchibo GmbH",
    "address": "Der Datenschutzbeauftragte\n√úberseering 18\n22297 Hamburg\nDeutschland",
    "phone": "+49 40 63 87 0",
    "email": "service@tchibo.de",
    "web": "https://www.tchibo.de/",
    "sources": [
        "https://www.tchibo.de/datenschutz-s400007324.html",
        "https://www.tchibo.de/impressum-bei-tchibo-c400001300.html"
    ]
}

=== Ainkill/data/data/ryanair.json
{
    "slug": "ryanair",
    "categories": [
        "travel"
    ],
    "name": "Ryanair DAC.",
    "runs": [
        "Ryanair App",
        "myRyanair-Konto"
    ],
    "address": "Corporate Head Office\nAirside Business Park\nSwords\nCo. Dublin\nIreland",
    "email": "impressum.de@ryanair.com",
    "web": "https://www.ryanair.com",
    "sources": [
        "https://www.ryanair.com/de/de/CorporateLinks/datenschutzbestimmung",
        "https://www.ryanair.com/de/de/CorporateLinks/unternehmensadresse-und-steuer-identifikationsnummer",
        "https://www.ryanair.com/de/de/nutzliche-infos/service-center/haufige-fragen/-Kontakt#0-0"
    ]
}
