=== Ainkill/data/schema.json
{
	"$schema": "http://json-schema.org/draft-03/schema#",
	"type": "object",
	"properties": {
		"slug": {
			"type": "string",
			"title": "Slug",
			"required": true
		},
		"categories": {
			"type": "array",
			"title": "Categories",
			"uniqueItems": true,
			"items": {
				"type": "string"
			}
		},
		"name": {
			"type": "string",
			"title": "Name",
			"required": true
		},
		"runs": {
			"type": "array",
			"title": "Runs",
			"uniqueItems": true,
			"items": {
				"type": "string"
			}
		},
		"address": {
			"type": "string",
			"title": "Address",
			"format": "text",
			"required": true
		},
		"phone": {
			"type": "string",
			"title": "Phone"
		},
		"fax": {
			"type": "string",
			"title": "Fax"
		},
		"email": {
			"type": "string",
			"title": "E-mail"
		},
		"web": {
			"type": "string",
			"title": "Website"
		},
		"sources": {
			"type": "array",
			"title": "Sources",
			"uniqueItems": true,
			"items": {
				"type": "string"
			},
			"required": true
		},
		"required-elements-access": {
			"type": "array",
			"title": "Access elements",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"desc": {
						"type": "string",
						"title": "Description",
						"required": true
					},
					"type": {
						"type": "string",
						"title": "Type",
						"required": true,
						"default": "input",
						"enum": [ "input", "textarea", "address" ]
					},
					"optional": {
						"type": "boolean",
						"title": "Optional?"
					}
				}
			}
		},
		"required-elements-erasure": {
			"type": "array",
			"title": "Erasure elements",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"desc": {
						"type": "string",
						"title": "Description",
						"required": true
					},
					"type": {
						"type": "string",
						"title": "Type",
						"required": true,
						"default": "input",
						"enum": [ "input", "textarea", "address" ]
					},
					"optional": {
						"type": "boolean",
						"title": "Optional?"
					}
				}
			}
		},
		"custom-access-template": {
			"type": "string",
			"title": "Custom access template"
		},
		"custom-erasure-template": {
			"type": "string",
			"title": "Custom erasure template"
		},
		"comments": {
			"type": "array",
			"title": "Comments",
			"items": {
				"type": "string",
				"format": "text"
			}
		}
	}
}

=== Ainkill/data/data/e-wie-einfach.json
{
    "slug": "e-wie-einfach",
    "categories": [
        "utility"
    ],
    "name": "E WIE EINFACH GmbH",
    "runs": [
        "Produkttest-Community (produkttest.e-wie-einfach.de)",
        "WieEinfach-Shop (www.wie-einfach.de)"
    ],
    "address": "Datenschutzbeauftragter\nSalierring 47 – 53\n50677 Köln\nDeutschland",
    "phone": "+49 221 1 77 37 0",
    "fax": "+49 221 1 77 37 2 10",
    "email": "datenschutzbeauftragter@e-wie-einfach.de",
    "web": "https://www.e-wie-einfach.de/",
    "sources": [
        "https://www.e-wie-einfach.de/datenschutz",
        "https://www.e-wie-einfach.de/impressum"
    ]
}

=== Ainkill/data/data/gfkl-inkasso.json
{
    "slug": "gfkl-inkasso",
    "categories": [
        "Inkasso"
    ],
    "name": "Lowell Financial Services GmbH",
    "runs": [
        "GFKL-Inkasso"
    ],
    "address": "Am Europa-Center 1b\n45145 Essen\nDeutschland",
    "phone": "+49 201 102 0",
    "fax": "+49 201 102 1199",
    "email": "webmaster@lowellgroup.de",
    "web": "https://www.gfkl.com",
    "sources": [
        "https://www.gfkl.com/datenschutz/"
    ]
}

=== Ainkill/data/data/deurema-inkasso.json
{
    "slug": "deurema-inkasso",
    "categories": [
        "Inkasso"
    ],
    "name": "DEUREMA Deutsche Rechnungsmanagement GmbH",
    "address": "Ludwig-Erhard-Stra√üe 4\n84034 Landshut\nDeutschland ",
    "phone": "+49 871 92318 10",
    "fax": "+49 871 92318 90",
    "email": "email@deurema.de",
    "web": "https://www.deurema.de",
    "sources": [
        "https://www.deurema.de/impressum-dl-infov.html"
    ]
}

=== Ainkill/data/data/riek-adressen.json
{
    "slug": "riek-adressen",
    "categories": [
        "addresses"
    ],
    "name": "Riek, direkt Marketing",
    "address": "Inh. Udo Riek\nHinter den HÃ¶fen 75\n31542 Bad Nenndorf\nDeutschland",
    "phone": "+49 57 23 79 30 68 4",
    "fax": "+49 163 56 07 57 6",
    "email": "info@riek-direkt.de",
    "web": "http://www.adressen-riek.de",
    "sources": [
        "http://www.adressen-riek.de/datenschutz/"
    ]
}

=== Ainkill/data/data/apple.json
{
    "slug": "apple",
    "categories": [
        "Handel",
        "Social Media"
    ],
    "name": "Apple Distribution International",
    "address": "Hollyhill Industrial Estate\nHollyhill, Cork\nRepublic of Ireland",
    "email": "contactus.de@euro.apple.com",
    "web": "https://www.apple.com",
    "sources": [
        "https://www.apple.com/legal/privacy/de-ww/",
        "https://www.apple.com/de/contact/"
    ]
}

=== Ainkill/data/data/check24.json
{
    "slug": "check24",
    "categories": [
        "ads",
        "insurance",
        "finance",
        "commerce",
        "telecommunication"
    ],
    "name": "CHECK24 Vergleichsportal GmbH",
    "runs": [
        "CHECK24 App",
        "CHECK24 Media GmbH",
        "CHECK24 Vergleichsportal für Versicherungsprodukte GmbH",
        "CHECK24 Versicherungsservice GmbH",
        "CHECK24 Vergleichsportal Finanzen GmbH",
        "CHECK24 Vergleichsportal Energie GmbH",
        "CHECK24 Vergleichsportal Telekommunikationsdienste GmbH",
        "CHECK24 Vergleichsportal Mobilfunk GmbH",
        "CHECK24 Vergleichsportal Mietwagen GmbH",
        "CHECK24 Vergleichsportal Reise GmbH",
        "CHECK24 Vergleichsportal Hotel GmbH",
        "CHECK24 Vergleichsportal Shopping GmbH",
        "CHECK24 Vergleichsportal Karten & Konten GmbH",
        "CHECK24 Services GmbH",
        "CHECK24 Vergleichsportal Autoteile GmbH",
        "CHECK24 Comparon GmbH",
        "CHECK24 Finanzservice GmbH",
        "TARIF CHECK24 GmbH",
        "CHECK24 Vergleichsportal Baufinanzierung GmbH"
    ],
    "address": "Erika-Mann-Str. 62 – 66\n80636 München\nDeutschland",
    "phone": "+49 89 200 047 1010",
    "fax": "+49 89 200 047 1011",
    "email": "webseite_datenschutz@check24.de",
    "web": "https://www.check24.de/",
    "sources": [
        "https://www.check24.de/popup/datenschutz/",
        "https://www.check24.de/unternehmen/impressum/"
    ]
}

=== Ainkill/data/data/branchenflat.json
{
    "slug": "branchenflat",
    "categories": [
        "Adressen"
    ],
    "name": "B2B Adressenmarketing GmbH",
    "address": "Datenschutzbeauftragter Herr Michael Merten\nIm Hollerfeld 12\n35325 MÃ¼cke\nDeutschland",
    "phone": "+49 180 15 0000 5",
    "fax": "+49 6401 9647238",
    "email": "ahlem.meddeb@b2badressenmarketing.de",
    "web": "http://branchenflat.de",
    "sources": [
        "http://branchenflat.de/de/datenschutz.html",
        "http://branchenflat.de/de/impressum.html"
    ]
}

=== Ainkill/data/data/casando.json
{
    "slug": "casando",
    "categories": [
        "Handel"
    ],
    "name": "Holz-Richter GmbH",
    "runs": [
        "Online-Baumarkt casando (www.casando.de)"
    ],
    "address": "Herrn Marcel Baldsiefen\nIndustriepark Klause\nSchmiedeweg 1\n51789 Lindlar\nDeutschland",
    "phone": "+49 22 66 47 35 610",
    "fax": "+49 22 66 47 35 869",
    "email": "info@casando.de",
    "web": "https://www.casando.de/",
    "sources": [
        "https://www.casando.de/info/datenschutz/",
        "https://www.casando.de/info/impressum/"
    ]
}
